name: Run Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: namespace-profile-tiny
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Run tests
      run: npm test

  docker-build:
    runs-on: namespace-profile-tiny
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ env.NSC_CONTAINER_REGISTRY }}/my-app:${{ github.sha }}
